### ISSUE TITLE
유저 아이디 요청 개선

### ISSUE THREAD

**Issue by Whale0928** [bottle-note/bottle-note-api-server#100]
유저 아이디를 가져오는 정적메소드 개선에 따른 수정이 필요합니다

수정 대상 
- 픽
- 위스키 조회
- 인기 위스키 조회

유저 아이디를 가져오는 부분이 있는 메소드가 있을 경우 댓글로 추가바랍니다

**Comment by 200wonman** [comment]
- 팔로우
- 닉네임변경
- 별점평가
- 문의
- 위스키 추가/수정 요청
- 신고
- 댓글
- 탈퇴

입니다!
