### ISSUE TITLE
create all entity class

### ISSUE THREAD

**Issue by Whale0928** [bottle-note/bottle-note-api-server#12]
### 작업사항
* 작업사항을 작성해주세요
* 체크리스트
    - [ ] 설계된 ERD를 가장 기본적인 형태로 엔티티 클래스를 구현합니다.
    - [ ] 각 엔티티에 적합한 패키지 구조를 구현합니다 ( domain 별 )

### 참고사항
* 도메인 메소드는 엔티티 클래스에 추가

**Comment by Whale0928** [comment]
![BottleNote](https://github.com/bottle-note/bottle-note-api-server/assets/75371249/674a3fda-d88a-4ba3-8361-3b4bb588f654)

**Comment by chadongmin** [comment]
아주 깔끔하게 설계된 ERD 네요
제가 느끼기에 테이블 명을 다 같이 한번 고민해보면 좋을 것 같습니다.
예를 들자면 , Rating이라는 테이블명은 저라면  '등급'을 나타내는 테이블이라고 바로 생각이 들 것 같아요. 테이블 명이 Star라면 더욱 직관적으로 별점 테이블이라는 것을 알 수 있을 것 같아요.
이처럼 다 같이 고민해보면 좋을 것 같다는 의견을 드려봅니다 ㅎㅎ.

**Comment by Whale0928** [comment]
2024 / 03 / 29
해당 이슈에 대한 오프라인 회의가 마무리 되었습니다.


## ERD 
- erd 개선 작업을 진행했다.
- 각 엔티티중  필요한 경우 추가적인 한글명 컬럼 필요 현재는 영어만 있음. (ex 위스키.)
- **tpye**의 경우 Enum으로 관리한다.  ( ex. 위스키 /  진 / 럼 /  꼬냑 )
- **Country** 의 경우 정규화한다.
	- 이유는 모든 나라를 파악하는건 시간이 아깝고  
	- 나라의 수가 많아 enum으로 관리하는건 X
	- 필수 값 : 나라 코드 , 대륙 코드 , 영문명 , 한글명 
	- 나라와 대륙등 etc 값들은 공통 테이블 하는걸 생각해보기.
- **distillery**의 경우 정규화를 한다 . 
	- 필수 값 :  영문명 , 한글명  , 로고 이미지 
-  Tier 의 경우 , 분석부터 진행 위스키,  진, 꼬냑등 술들의 tier 기준을 표로 만드는 작업 부터 한다.
	-  필수적인 데이터 
		- type ( 위스키 ,꼬냑 ..) 
		- tier (12, 15 , XO , VSOP .. )
- size는 삭제 사용 가치가 없어 보임.
- cask는 단순 문자열로  저장
- 삭제의 걔념이 있는 모든 테이블은 논리적 삭제를 한다. 
	- status 
	- 삭제 후 modify 로 관리
- report의 경우 user / review 를 타입을 삭제후 각각의 신고 테이블로 나눈다.
- review는 수정작업이 필요하다.
	- 장소 값은  => 우편번호 / 주소 / 상세주소 3개로 확장 
	- 이미지는 리뷰와 1:n관계가 될수 있다 => 테이블 정규화가 필요하다.
	- 기존 이미지 컬럼은 리뷰의 썸네일으로 활용할 수도 있다.  추가적인 디자인 기획 회의에 따라 삭제 가능성 높음.
	- view_count 추가가 필요하다. (상세 조회 시)

##### 추가되어야하는 테이블 

- 댓글 테이블이 필요.
- 게시판에 대한 엔티티 추가 필요  => notice (공지사항 , 이벤트 , 점검 등 ...)
	- 이벤트가 긴급공지는 푸시 서비스를 추가적으로 구현할 수도 있다.  ( 추후 앱으로 감쌀때 고려 )
	- 이미지를 등록 할 수 있다.
	- notice
		- title
		- content
		- category
		- view_count
- 검색 히스토리
- 검색+찜+리뷰+레이팅 등을 혼합한 분석용 테이블
- 분석 테이블을 기준으로 배치용 best 테이블  


### CSV
- 컬럼명은 모두 erd와 매칭 필요
- 영문명에 대한 한글 매핑 처리 필요
	- Glen Grant 15 => 글렌 그랜트
- category 는 enum으로 분리하자.
- Stated Age 는 정규식으로 숫자만 추출.
- abv는 소수점 한자리수 까지 정규식을 추가한다.
- Stated Age 의 경우 꼬약은 XO, VSOP등의 문자열 , 타 알코올은 정수로 관리하기 떄문에. Enum으로 관리 
- 기존 CSV에는 영여 이름만 있는데. 이를 APi를 번역 
- 테이스팅 태그의  / 를 제외한 공백,특수 문자는 모두  _ (언더바) 기호로 변환한다.
	- / 기호는 테이스팅 태그 한 문장을 논리적으로 나누는 기호로 결정.


### etc.
- 인증 회원 -> 바텐더 , 인기 리뷰어등 개성을 뱃지 걔념으로 추가하는  서비스를 기획.


추가적인 테이블 설계 작업은 새로운 이슈를 오픈하여 작업합니다.
