### ISSUE TITLE
Review 관련 API 리팩토링

### ISSUE THREAD

**Issue by chadongmin** [bottle-note/bottle-note-api-server#142]
## 작업사항

* Review 도메인에서 custom 패키지 하위의 중복된 서브쿼리를 제거하여 서포트 클래스로 합칩니다.
* 인터페이스 메소드에 대한 동작에 상세한 주석을 작성합니다.
* 기존 DTO Projection에서 Field injection 방식에서 생성자 방식으로 수정합니다.
* 메서드 명을 정확하게 수정합니다. (단일 조회는 s붙이지 않고, 복수 조회는 s붙이는 형태)

**Comment by Whale0928** [comment]
- 프로젝트를 정확하게 등록하죠 누락된 정보가 있네요.
- 작성 내용을 좀더 정확하게 작성하죠 . `ex) custom 패키지의 분할된 레포지토리를 합치도록 개선 , 중복된 서브 쿼리를 개선 , 서포트 클래스의 ~~ 같이 `

**Comment by Whale0928** [comment]
추가적으로 `인터페이스 메소드에 동작에 대한 상세한 주석 달기`

**Comment by chadongmin** [comment]
상세하게 수정했습니다!
