### ISSUE TITLE
share tech-spec 

### ISSUE THREAD

**Issue by Whale0928** [bottle-note/bottle-note-api-server#18]
### 작업사항
* create tech-spec example documentation
* write sample documentation

 ### 작업 이유
* tech-spec은 개발 할때 서로간의 싱크를 맞추고 , 개선하기 가장 좋은 문서화라고 생각합니다.
* 스펙의 탬플릿을 관리하고 공유하는 예제를 나눠 효율적인 개발 문화를 만들기 위해 도입합니다.

### 참고사항
* `docs/tech-spec/* `경로에 포함됩니다.

**Comment by Whale0928** [comment]
docs/tech-spec 폴더의 ReadMe.md를 추가했습니다.

**Comment by 200wonman** [comment]
넵! 확인했습니다

**Comment by Whale0928** [comment]
공유 완료로 이슈 종료합니다.
