### ISSUE TITLE
ERD 추가 개선 작업

### ISSUE THREAD

**Issue by Whale0928** [bottle-note/bottle-note-api-server#21]
### 작업사항
* #12  해당 이슈를 통해 개선된 ERD 내용을 수정 적용하는 이슈입니다.
* 체크리스트
**ERD 개선 작업**
- [x] 각 엔티티에 한글명 영어명 컬럼 분리 추가
- [ ] Enum으로 type 관리
- [x] 공통 테이블로 나라, 대륙 등 관리 고려
- [x] 논리적 삭제 구현
- [x] Review 수정 작업
   - [x] 장소 확장 (우편번호, 주소, 상세주소)
   - [x] View count 추가 (필요한 테이블에 경우)

**테이블 분할**
- [x] Country 테이블 추가
- [x] Distillery 테이블 추가
- [x] Tier 테이블 추가
- [x] Report 테이블 추가
- [x] 이미지 테이블 정규화
- [x] 댓글 테이블 추가
- [x] Notice 엔티티 추가
- [ ] 검색 히스토리 테이블 추가
- [ ] 분석용 테이블 및 배치용 best 테이블 추가

**Comment by Whale0928** [comment]
admin / search_history / analysis 테이블은 구조는 기억하되 진행하며 구체화하는 것으로 합니다.

검색 값 분석 값등은 기능 개발을 진행하며 정리하는것이 더욱 적절해보입니다.

**Comment by 200wonman** [comment]
넵 잘 확인했습니다.
로지컬 피지컬 한글 영문 표기만 조금 더 수정해 주시면 될 것 같습니다~

**Comment by chadongmin** [comment]
네 확인했습니다. 
제 생각해도 admin / search_history / analysis 테이블은 지금 당장 설계단계에서 너무 정확하게 정하기 보다는, 기능 개발하며 정하는 것이 더 좋을 것 같아요.
고생하셨습니다~

**Comment by Whale0928** [comment]
해당 내용은 작업 대상이 아닙니다.
컬럼의 데이터만 보면 됩니다.
