### ISSUE TITLE
Follow 관련 API 리팩토링 및 알콜 조회 시 Follow한 유저 정보 노출

### ISSUE THREAD

**Issue by chadongmin** [bottle-note/bottle-note-api-server#287]
## 작업사항

- Follow 관련 API 리팩토링 및 알콜 조회 시 Follow한 유저 정보 노출

**Comment by Whale0928** [comment]
#### list up
- 팔로워 관련 API 리스트업
- 팔로우 관련 API 리스트업
- 팔로워 정보를 위한 퍼사드 클래스 구현
- 테스트 케이스 구현
