### ISSUE TITLE
bottle-note erd 테이블 추가/수정

### ISSUE THREAD

**Issue by 200wonman** [bottle-note/bottle-note-api-server#42]
### 리뷰 공감 table 및 위스키 image_url culmn 추가
* 작업사항을 작성
* 체크리스트
    - [x] 리뷰의 공감 테이블을 만들어야함.
    - [x] alcohol의 위스키  image_url 부재 : 섬네일 / 상세
    - [x] 그밖에 놓친 컬럼 혹은 테이블 체크

**Comment by Whale0928** [comment]
- 수정일/수정자/생성일/생성자 null 허용
- 코멘트 없는 행들 코멘트 추가
