### ISSUE TITLE
OAuth2 로그인 기능 테스트 코드 및 RestDocs 작성

### ISSUE THREAD

**Issue by chadongmin** [bottle-note/bottle-note-api-server#66]
### 작업사항
테스트코드 및 RestDocs를 작성합니다.
* 체크리스트
    - [x] 테스트 코드를 작성합니다.
    - [x] 테스트코드 기반으로 RestDocs를 작성합니다.

### 작업 이유
* 작성한 코드의 안정성을 검증하기 위해 테스트코드를 작성합니다. 
* 테스트코드를 기반으로 API 문서화를 진행하여 프론트엔드 구성원에게 제공하기 위함입니다.

**Comment by Whale0928** [comment]
프로젝트 옆 `+4 more`  선택 후 나머지 정보들 설정해주세요.
